language: php
php:
  - 5.5
  - 5.4

before_script: composer install --prefer-source

script: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php ./vendor/bin/coveralls
